### ISSUE TITLE
user/views的返回，这一行的KEY写成了date

### ISSUE THREAD

**Issue by RAND1925** [TJCatFood/backend#35]
https://github.com/TJCatFood/backend/blob/6f823c52d62420fcbdb277fe21c983aa478992f2/catfood/user/views.py#L106

**Comment by RAND1925** [comment]
还有，isSuccess == false的时候，返回error还是data

**Comment by Moreonenight** [comment]
是打字错误；返回error；[#37](https://github.com/TJCatFood/backend/pull/37)改正了这两处错误。
